#!/bin/bash

[ ! -n "$1" ] && echo "Please supply New Relic license key" && exit 1

echo deb http://apt.newrelic.com/debian/ newrelic non-free >> /etc/apt/sources.list.d/newrelic.list
wget -O- https://download.newrelic.com/548C16BF.gpg | apt-key add -

apt-get update
apt-get install -y newrelic-sysmond

nrsysmond-config --set license_key="$1"
/etc/init.d/newrelic-sysmond start
